- react-app/ccf/.gitignore
- react-app/ccf/package-lock.json
- react-app/ccf/package.json
- react-app/ccf/src/index.tsx
- modified gitignore to never push firebase_config folder
- added boilerplate code to index.tsx
> Firebase Initial Setup

- .firebaserc
- .gitignore
- firebase.json
- react-app/ccf/src/index.tsx
Added Firestore, Cloud storage, and Auth connection to emulator when testing locally. To test locally make .env file and set a new variable called LOCAL_TESTING=true.
> added emulator connection to index.tsx

- firestore.rules
- functions/src/index.ts
- functions/tsconfig.json
- react-app/ccf/src/index.tsx
- react-app/ccf/src/initialize-test-environment.ts
created a better test environment with test accounts for admin, applicant and reviewer and added their custom claims. Also added the firestore entries for each test user. However did not add dummy applications because I didn't want to change code in the applicant dashboard when it wasn't completely up to date yet and the reviewer dashboard also wasn't finished. When they eventually get finished, I can add the dummy applications to the test environment.
> Created a better test environment

- react-app/ccf/src/App.tsx
- react-app/ccf/src/backend/applicant-form-submit.ts
Moved submit form backend calls to new backend folder. Fixed repeat imports in App.tsx
> Some small organizational and bug fixes

- react-app/ccf/package-lock.json
- react-app/ccf/package.json
- react-app/ccf/src/components/banner/Banner.css
- react-app/ccf/src/components/banner/Banner.tsx
- react-app/ccf/src/pages/applicant-dashboard/ApplicantDashboard.tsx
- [X ] Bug fix (non-breaking change which fixes an issue)
- [ X] Frontend New feature (non-breaking change which adds functionality)
- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my code
- [X ] I have used components when necessary, minimize in-line CSS, and define types in a separate file within the types folder
- [X ] Tested components and UI elements across various resolutions and display sizes using Chrome DevTools to ensure proper rendering and functionality.
- [ X] My changes generate no new errors to the best of my knowledge
- [ X] There are no major merge conflicts …
> Banner is back!

- react-app/ccf/src/components/sidebar/Sidebar.tsx
- react-app/ccf/src/pages/applicant-dashboard/ApplicantDashboard.tsx
- react-app/ccf/src/pages/reviewer-dashboard/ReviewerDashboard.tsx
- react-app/ccf/src/pages/settings/settings.tsx
> quick fix to remove unnused role prop in sidebar

- react-app/ccf/src/App.tsx
- react-app/ccf/src/pages/settings/AdminSettings.tsx
- react-app/ccf/src/pages/settings/ApplicantSettings.tsx
- react-app/ccf/src/pages/settings/ReviewerSettings.tsx
- react-app/ccf/src/types/sidebar-types.ts
I tested this through the different roles' logins to make sure the appropriate settings pages were showing up. 
This is the reviewer settings page (the search bar has the /reviewer/settings)
This is the applicant settings page (the search bar has the /applicant/settings)
This is the admin settings page (the search bar has the /admin/settings)
- [] I have commented my code, particularly in hard-to-understand areas
> Role specific settings pages and routing

- react-app/ccf/src/App.tsx
- react-app/ccf/src/components/Routing/DefaultRoute.tsx
- react-app/ccf/src/types/sidebar-types.ts
> restructured routes by user role

- react-app/ccf/package-lock.json
- react-app/ccf/package.json
> high sev vuln update

- react-app/ccf/src/App.tsx
- react-app/ccf/src/pages/admin-database/AdminDatabase.tsx
- react-app/ccf/src/pages/grant-awards/GrantAwards.css
- react-app/ccf/src/pages/grant-awards/GrantAwards.tsx
- react-app/ccf/src/types/application-types.ts
Connected admin dashboard with backend
Connected award recommendations with backend
> Link admin database backend

- react-app/ccf/src/types/application-types.ts
- react-app/ccf/src/types/usertypes.ts
- react-app/ccf/src/users/usermanager.ts
> cleanup assign-reviewer branch

- react-app/ccf/src/components/applications/ApplicationBox.css
- react-app/ccf/src/pages/create-acc-applicants/CreateAccApplicant.tsx
- react-app/ccf/src/pages/create-acc-reviewer/CreateAccReviewer.css
- react-app/ccf/src/pages/create-acc-reviewer/CreateAccReviewer.tsx
> Add pictures for reviewer account creation (rebase)

- react-app/ccf/src/pages/application-form/ApplicationForm.tsx
- react-app/ccf/src/pages/application-form/NRApplicationForm.tsx
> Fix navigator endpoints for submission redirects

- react-app/ccf/src/App.tsx
- react-app/ccf/src/components/Routing/AdminProtectedRoute.tsx
- react-app/ccf/src/components/Routing/ApplicantProtectedRoute.tsx
- react-app/ccf/src/components/Routing/ReviewerProtectedRoute.tsx
> added page authentication using already made routing

- react-app/ccf/src/backend/applicant-form-submit.ts
- react-app/ccf/src/backend/reviews.ts
- react-app/ccf/src/components/applications/CoverPageModal.tsx
- react-app/ccf/src/pages/application-form/ApplicationForm.tsx
- react-app/ccf/src/pages/application-form/NRApplicationForm.tsx
- react-app/ccf/src/pages/application-form/subquestions/Review.tsx
- react-app/ccf/src/storage/storage.ts
- react-app/ccf/src/types/review-types.ts
> backend functions for reviews

- react-app/ccf/src/App.tsx
- react-app/ccf/src/backend/applicant-form-submit.ts
- react-app/ccf/src/backend/application-cycle.ts
- react-app/ccf/src/backend/application-filters.ts
- react-app/ccf/src/backend/faq-handler.ts
- react-app/ccf/src/components/applications/CoverPageModal.tsx
- react-app/ccf/src/pages/admin-database/AdminDatabase.tsx
- react-app/ccf/src/pages/admin-edit-info/AdminEditInformation.tsx
- react-app/ccf/src/pages/applicant-dashboard/ApplicantDashboard.tsx
- react-app/ccf/src/pages/application-form/subquestions/SubForm.css
- react-app/ccf/src/pages/application-review/ApplicationReviewReadOnly.tsx
- react-app/ccf/src/pages/assign-reviewers-page/AssignReviewers.tsx
- react-app/ccf/src/pages/grant-awards/GrantAwards.tsx
- react-app/ccf/src/pages/reviewer-all-applications/AllApplications.tsx
- react-app/ccf/src/pages/reviewer-dashboard/ReviewerDashboard.tsx
- react-app/ccf/src/pages/settings/settings.tsx
- react-app/ccf/src/types/application-types.ts
- react-app/ccf/src/types/sidebar-types.ts
- react-app/ccf/src/utils/stringfuncs.ts
Merging one of the show-case demo branches to the main branch
> Assign reviewer v2

- react-app/ccf/package-lock.json
- react-app/ccf/package.json
- react-app/ccf/src/App.tsx
- react-app/ccf/src/pages/application-form/ApplicationForm.css
- react-app/ccf/src/pages/application-form/ApplicationForm.tsx
- react-app/ccf/src/pages/application-form/NRApplicationForm.tsx
- react-app/ccf/src/pages/application-form/subquestions/Information.tsx
- react-app/ccf/src/pages/application-form/subquestions/NRInformation.tsx
- react-app/ccf/src/pages/application-form/subquestions/SubForm.css
- react-app/ccf/src/pages/create-acc-applicants/CreateAccApplicant.tsx
- react-app/ccf/src/pages/create-acc-reviewer/CreateAccReviewer.tsx
- react-app/ccf/src/post-grant-report/post-grant-report.tsx
> Application type checking

- react-app/ccf/src/backend/application-cycle.ts
- react-app/ccf/src/pages/applicant-dashboard/ApplicantDashboard.tsx
- react-app/ccf/src/pages/application-form/ApplicationForm.tsx
- react-app/ccf/src/pages/application-form/NRApplicationForm.tsx
> disabled buttons for submitting apps if apps closed (only frontend)

- react-app/ccf/package-lock.json
- react-app/ccf/package.json
- react-app/ccf/src/App.tsx
- react-app/ccf/src/components/decisions/decisionBox.css
- react-app/ccf/src/components/decisions/decisionBox.tsx
- react-app/ccf/src/pages/applicant-dashboard/ApplicantDashboard.tsx
- react-app/ccf/src/pages/applicant-decisions/ApplicantDecisions.css
- react-app/ccf/src/pages/applicant-decisions/ApplicantDecisions.tsx
- react-app/ccf/src/pages/settings/ApplicantSettings.tsx
- react-app/ccf/src/types/sidebar-types.ts
> Applicant dash results

- react-app/ccf/src/components/decisions/decisionBox.tsx
> use isAccepted bool instead of status
